### ISSUE TITLE
XWayland crashing causes a deadlock

### ISSUE THREAD

**Issue by colinmarc** [Smithay/smithay#1209]
I haven't been able to figure out why exactly, but I think it has to do with calling `kill_client' from the client killed callback, and as far as I can tell concerns a single thread.

https://github.com/Smithay/smithay/blob/cd0bb24f92e0ef0f94703c3cc189705dead8db1a/src/xwayland/xserver.rs#L380-L382

Here's a backtrace from a hung process:

```
Thread 19 (Thread 0x7fffdd3ee6c0 (LWP 1162961) "mm-server"):
#0  0x00007ffff572358d in syscall () from /nix/store/gqghjch4p1s69sv4mcjksb2kb65rwqjy-glibc-2.38-23/lib/libc.so.6
#1  0x000055555566f394 in std::sys::unix::locks::futex_mutex::Mutex::lock_contended::h8ffc58d996a1654c ()
#2  0x0000555555f5dc5e in std::sys::unix::locks::futex_mutex::Mutex::lock (self=0x7fff90000bb0) at /build/rustc-1.72.1-src/library/std/src/sys/unix/locks/futex_mutex.rs:28
#3  0x0000555555f5dc8f in std::sync::mutex::Mutex<(dyn wayland_backend::rs::server_impl::handle::ErasedState + core::marker::Send)>::lock<(dyn wayland_backend::rs::server_impl::handle::ErasedState + core::marker::Send)> (self=...) at /build/rustc-1.72.1-src/library/std/src/sync/mutex.rs:273
#4  0x0000555555f6f480 in wayland_backend::rs::server_impl::handle::InnerHandle::kill_client (self=0x7fffdd3e5f10, client_id=..., reason=...) at src/rs/server_impl/handle.rs:214
#5  0x0000555555e188f7 in wayland_backend::rs::server::Handle::kill_client (self=0x7fffdd3e5f10, client_id=..., reason=...) at /home/colinmarc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wayland-backend-0.1.2/src/rs/../server_api.rs:414
#6  0x0000555555e27d02 in smithay::xwayland::xserver::Inner::shutdown (self=0x7fff9002a778) at src/xwayland/xserver.rs:381
#7  0x0000555555e27421 in smithay::xwayland::xserver::{impl#2}::disconnected (self=0x7fff9002ac10, _client_id=..., _reason=...) at src/xwayland/xserver.rs:226
#8  0x000055555579eb89 in wayland_backend::rs::server_impl::client::Client<mm_server::compositor::State>::kill<mm_server::compositor::State> (self=0x7fff9021dce0, reason=...) at /home/colinmarc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wayland-backend-0.1.2/src/rs/server_impl/client.rs:315
#9  0x000055555579adee in wayland_backend::rs::server_impl::client::Client<mm_server::compositor::State>::next_request<mm_server::compositor::State> (self=0x7fff9021dce0) at /home/colinmarc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wayland-backend-0.1.2/src/rs/server_impl/client.rs:353
#10 <dispatch_clients in compositor code>
```

**Comment by colinmarc** [comment]
I updated smithay and it appears this issue has already been fixed, sorry about that!

**Comment by colinmarc** [comment]
Err, I got confused - this still appears on trunk smithay, but only using the rust version of wayland-sys, not with the C version.
