### ISSUE TITLE
drm: Retry commit on `EBUSY`

### ISSUE THREAD

**Issue by PolyMeilex** [Smithay/smithay#201]
Unwrap (ContextLost) happens here: https://github.com/Smithay/smithay/blob/61fecb44cfcd3ab4cd9f2133baf64e93b2afd692/anvil/src/udev.rs#L470

Error originates from glium context but I don't think that glium is at fault here.

## System Info:
**Distro:** `Arch Linux`
**GPU:** `GTX 970` (+`Intel HD Graphics`, but I believe that it is not used at all)
**Drivers:** `Nouveau`
I'm using `Logind`

# Full Log
```
Apr 21 17:13:40.054 INFO Starting anvil on a tty using udev
Apr 21 17:13:40.054 INFO Listening on wayland socket, name: wayland-0
Apr 21 17:13:40.054 INFO Trying to create logind session, session_type: auto, smithay_module: backend_session_auto
Apr 21 17:13:40.098 INFO DrmDevice initializing, smithay_module: backend_drm
Apr 21 17:13:40.098 WARN Unable to become drm master, assuming unpriviledged mode, smithay_module: backend_drm
Apr 21 17:13:40.098 DEBG Creating gbm device, smithay_module: backend_gbm
Apr 21 17:13:40.189 DEBG Creating egl context from device, smithay_module: backend_egl
Apr 21 17:13:40.245 DEBG EGL No-Display Extensions: ["EGL_EXT_platform_base", "EGL_EXT_device_base", "EGL_EXT_device_enumeration", "EGL_EXT_device_query", "EGL_KHR_client_get_all_proc_addresses", "EGL_EXT_client_extensions", "EGL_KHR_debug", "EGL_KHR_platform_x11", "EGL_EXT_platform_x11", "EGL_EXT_platform_device", "EGL_KHR_platform_wayland", "EGL_EXT_platform_wayland", "EGL_MESA_platform_gbm", "EGL_MESA_platform_surfaceless"], smithay_module: renderer_egl, smithay_module: backend_egl
Apr 21 17:13:40.246 INFO EGL Initialized, smithay_module: renderer_egl, smithay_module: backend_egl
Apr 21 17:13:40.247 INFO EGL Version: (1, 5), smithay_module: renderer_egl, smithay_module: backend_egl
Apr 21 17:13:40.247 INFO EGL Extensions: ["EGL_ANDROID_blob_cache", "EGL_EXT_buffer_age", "EGL_EXT_create_context_robustness", "EGL_EXT_image_dma_buf_import", "EGL_EXT_image_dma_buf_import_modifiers", "EGL_KHR_cl_event2", "EGL_KHR_config_attribs", "EGL_KHR_create_context", "EGL_KHR_create_context_no_error", "EGL_KHR_fence_sync", "EGL_KHR_get_all_proc_addresses", "EGL_KHR_gl_colorspace", "EGL_KHR_gl_renderbuffer_image", "EGL_KHR_gl_texture_2D_image", "EGL_KHR_gl_texture_3D_image", "EGL_KHR_gl_texture_cubemap_image", "EGL_KHR_image", "EGL_KHR_image_base", "EGL_KHR_image_pixmap", "EGL_KHR_no_config_context", "EGL_KHR_reusable_sync", "EGL_KHR_surfaceless_context", "EGL_EXT_pixel_format_float", "EGL_KHR_wait_sync", "EGL_MESA_configless_context", "EGL_MESA_drm_image", "EGL_MESA_image_dma_buf_export", "EGL_MESA_query_driver", "EGL_WL_bind_wayland_display", ""], smithay_module: renderer_egl, smithay_module: backend_egl
Apr 21 17:13:40.247 INFO Connected: HDMIA
Apr 21 17:13:40.247 INFO Connected: DisplayPort
Apr 21 17:13:40.247 INFO Initializing EglSurface, smithay_module: backend_egl
Apr 21 17:13:40.247 DEBG Trying to initialize EGL with OpenGLES 3.0, smithay_module: renderer_egl, smithay_module: renderer_egl, smithay_module: backend_egl
Apr 21 17:13:40.247 INFO Selected color format: PixelFormat { hardware_accelerated: true, color_bits: 24, alpha_bits: 8, depth_bits: 24, stencil_bits: 8, stereoscopy: false, multisampling: None, srgb: false }, smithay_module: renderer_egl, smithay_module: backend_egl
Apr 21 17:13:40.258 INFO EGL context created, smithay_module: renderer_egl, smithay_module: renderer_egl, smithay_module: renderer_egl, smithay_module: backend_egl
Apr 21 17:13:40.258 INFO Initializing GbmSurface, smithay_module: backend_gbm
Apr 21 17:13:40.258 DEBG EGL surface successfully created, smithay_module: renderer_egl, smithay_module: backend_egl
Apr 21 17:13:40.567 INFO Initializing EglSurface, smithay_module: backend_egl
Apr 21 17:13:40.567 DEBG Trying to initialize EGL with OpenGLES 3.0, smithay_module: renderer_egl, smithay_module: renderer_egl, smithay_module: backend_egl
Apr 21 17:13:40.567 INFO Selected color format: PixelFormat { hardware_accelerated: true, color_bits: 24, alpha_bits: 8, depth_bits: 24, stencil_bits: 8, stereoscopy: false, multisampling: None, srgb: false }, smithay_module: renderer_egl, smithay_module: backend_egl
Apr 21 17:13:40.567 INFO EGL context created, smithay_module: renderer_egl, smithay_module: renderer_egl, smithay_module: renderer_egl, smithay_module: backend_egl
Apr 21 17:13:40.568 INFO Initializing GbmSurface, smithay_module: backend_gbm
Apr 21 17:13:40.568 DEBG EGL surface successfully created, smithay_module: renderer_egl, smithay_module: backend_egl
Apr 21 17:13:40.579 INFO Initializing EglSurface, smithay_module: backend_egl
Apr 21 17:13:40.579 DEBG Trying to initialize EGL with OpenGLES 3.0, smithay_module: renderer_egl, smithay_module: renderer_egl, smithay_module: backend_egl
Apr 21 17:13:40.579 INFO Selected color format: PixelFormat { hardware_accelerated: true, color_bits: 24, alpha_bits: 8, depth_bits: 24, stencil_bits: 8, stereoscopy: false, multisampling: None, srgb: false }, smithay_module: renderer_egl, smithay_module: backend_egl
Apr 21 17:13:40.579 INFO EGL context created, smithay_module: renderer_egl, smithay_module: renderer_egl, smithay_module: renderer_egl, smithay_module: backend_egl
Apr 21 17:13:40.580 INFO Initializing GbmSurface, smithay_module: backend_gbm
Apr 21 17:13:40.580 DEBG EGL surface successfully created, smithay_module: renderer_egl, smithay_module: backend_egl
Apr 21 17:13:40.585 DEBG Importing cursor, crtc: crtc::Handle(63), smithay_module: backend_gbm
[src/backend/drm/legacy/surface.rs:270] x = Unknown {
    errno: EBUSY,
}
Apr 21 17:13:40.586thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ContextLost ', DEBGanvil/src/udev.rs :Commiting new state470:, 21crtc
:note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
 crtc::Handle(63), smithay_module: backend_gbm
Apr 21 17:13:40.586 DEBG Setting screen, crtc: crtc::Handle(63), smithay_module: backend_drm
Apr 21 17:13:40.586 INFO Closing logind session, vt: None, seat: seat0, id: 1, session_type: logind, smithay_module: backend_session, session_type: auto, smithay_module: backend_session_auto
Apr 21 17:13:40.608 INFO Dropping device: Some("/dev/dri/card1"), smithay_module: backend_drm
Apr 21 17:13:40.608 ERRO Failed to reset crtc (crtc::Handle(55)). Error: permission denied, smithay_module: backend_drm
Apr 21 17:13:40.608 ERRO Failed to reset crtc (crtc::Handle(47)). Error: permission denied, smithay_module: backend_drm
```

**Comment by Drakulix** [comment]
Cursor import seems to fail on one of your surfaces, which anvil does not handle right now.
Does it also happen if you unplug one of your monitors?

**Comment by PolyMeilex** [comment]
Good idea, with one monitor it works.
Here is what happens when I connect monitor when anvil is running
```
Apr 21 20:39:20.538 INFO Starting anvil on a tty using udev
Apr 21 20:39:20.538 INFO Listening on wayland socket, name: wayland-0
Apr 21 20:39:20.539 INFO Trying to create logind session, session_type: auto, smithay_module: backend_session_auto
Apr 21 20:39:20.722 INFO DrmDevice initializing, smithay_module: backend_drm
Apr 21 20:39:20.722 WARN Unable to become drm master, assuming unpriviledged mode, smithay_module: backend_drm
Apr 21 20:39:20.722 DEBG Creating gbm device, smithay_module: backend_gbm
Apr 21 20:39:20.776 DEBG Creating egl context from device, smithay_module: backend_egl
Apr 21 20:39:20.783 DEBG EGL No-Display Extensions: ["EGL_EXT_platform_base", "EGL_EXT_device_base", "EGL_EXT_device_enumeration", "EGL_EXT_device_query", "EGL_KHR_client_get_all_proc_addresses", "EGL_EXT_client_extensions", "EGL_KHR_debug", "EGL_KHR_platform_x11", "EGL_EXT_platform_x11", "EGL_EXT_platform_device", "EGL_KHR_platform_wayland", "EGL_EXT_platform_wayland", "EGL_MESA_platform_gbm", "EGL_MESA_platform_surfaceless"], smithay_module: renderer_egl, smithay_module: backend_egl
Apr 21 20:39:20.784 INFO EGL Initialized, smithay_module: renderer_egl, smithay_module: backend_egl
Apr 21 20:39:20.784 INFO EGL Version: (1, 5), smithay_module: renderer_egl, smithay_module: backend_egl
Apr 21 20:39:20.784 INFO EGL Extensions: ["EGL_ANDROID_blob_cache", "EGL_EXT_buffer_age", "EGL_EXT_create_context_robustness", "EGL_EXT_image_dma_buf_import", "EGL_EXT_image_dma_buf_import_modifiers", "EGL_KHR_cl_event2", "EGL_KHR_config_attribs", "EGL_KHR_create_context", "EGL_KHR_create_context_no_error", "EGL_KHR_fence_sync", "EGL_KHR_get_all_proc_addresses", "EGL_KHR_gl_colorspace", "EGL_KHR_gl_renderbuffer_image", "EGL_KHR_gl_texture_2D_image", "EGL_KHR_gl_texture_3D_image", "EGL_KHR_gl_texture_cubemap_image", "EGL_KHR_image", "EGL_KHR_image_base", "EGL_KHR_image_pixmap", "EGL_KHR_no_config_context", "EGL_KHR_reusable_sync", "EGL_KHR_surfaceless_context", "EGL_EXT_pixel_format_float", "EGL_KHR_wait_sync", "EGL_MESA_configless_context", "EGL_MESA_drm_image", "EGL_MESA_image_dma_buf_export", "EGL_MESA_query_driver", "EGL_WL_bind_wayland_display", ""], smithay_module: renderer_egl, smithay_module: backend_egl
Apr 21 20:39:20.784 INFO Connected: HDMIA
Apr 21 20:39:20.785 INFO Initializing EglSurface, smithay_module: backend_egl
Apr 21 20:39:20.785 DEBG Trying to initialize EGL with OpenGLES 3.0, smithay_module: renderer_egl, smithay_module: renderer_egl, smithay_module: backend_egl
Apr 21 20:39:20.785 INFO Selected color format: PixelFormat { hardware_accelerated: true, color_bits: 24, alpha_bits: 8, depth_bits: 24, stencil_bits: 8, stereoscopy: false, multisampling: None, srgb: false }, smithay_module: renderer_egl, smithay_module: backend_egl
Apr 21 20:39:20.786 INFO EGL context created, smithay_module: renderer_egl, smithay_module: renderer_egl, smithay_module: renderer_egl, smithay_module: backend_egl
Apr 21 20:39:20.786 INFO Initializing GbmSurface, smithay_module: backend_gbm
Apr 21 20:39:20.786 DEBG EGL surface successfully created, smithay_module: renderer_egl, smithay_module: backend_egl
Apr 21 20:39:20.799 DEBG Importing cursor, crtc: crtc::Handle(47), smithay_module: backend_gbm
Apr 21 20:39:20.799 DEBG Commiting new state, crtc: crtc::Handle(47), smithay_module: backend_gbm
Apr 21 20:39:20.799 DEBG Setting screen, crtc: crtc::Handle(47), smithay_module: backend_drm
Apr 21 20:39:20.811 INFO DrmDevice initializing, smithay_module: backend_drm
Apr 21 20:39:20.811 WARN Unable to become drm master, assuming unpriviledged mode, smithay_module: backend_drm
Apr 21 20:39:20.811 DEBG Creating gbm device, smithay_module: backend_gbm
Apr 21 20:39:20.817 DEBG Creating egl context from device, smithay_module: backend_egl
Apr 21 20:39:20.817 DEBG EGL No-Display Extensions: ["EGL_EXT_platform_base", "EGL_EXT_device_base", "EGL_EXT_device_enumeration", "EGL_EXT_device_query", "EGL_KHR_client_get_all_proc_addresses", "EGL_EXT_client_extensions", "EGL_KHR_debug", "EGL_KHR_platform_x11", "EGL_EXT_platform_x11", "EGL_EXT_platform_device", "EGL_KHR_platform_wayland", "EGL_EXT_platform_wayland", "EGL_MESA_platform_gbm", "EGL_MESA_platform_surfaceless"], smithay_module: renderer_egl, smithay_module: backend_egl
Apr 21 20:39:20.818 INFO EGL Initialized, smithay_module: renderer_egl, smithay_module: backend_egl
Apr 21 20:39:20.818 INFO EGL Version: (1, 4), smithay_module: renderer_egl, smithay_module: backend_egl
Apr 21 20:39:20.818 INFO EGL Extensions: ["EGL_ANDROID_blob_cache", "EGL_ANDROID_native_fence_sync", "EGL_EXT_buffer_age", "EGL_EXT_create_context_robustness", "EGL_EXT_image_dma_buf_import", "EGL_EXT_image_dma_buf_import_modifiers", "EGL_KHR_config_attribs", "EGL_KHR_create_context", "EGL_KHR_create_context_no_error", "EGL_KHR_fence_sync", "EGL_KHR_get_all_proc_addresses", "EGL_KHR_gl_colorspace", "EGL_KHR_gl_renderbuffer_image", "EGL_KHR_gl_texture_2D_image", "EGL_KHR_gl_texture_3D_image", "EGL_KHR_gl_texture_cubemap_image", "EGL_KHR_image", "EGL_KHR_image_base", "EGL_KHR_image_pixmap", "EGL_KHR_no_config_context", "EGL_KHR_reusable_sync", "EGL_KHR_surfaceless_context", "EGL_EXT_pixel_format_float", "EGL_KHR_wait_sync", "EGL_MESA_configless_context", "EGL_MESA_drm_image", "EGL_MESA_image_dma_buf_export", "EGL_MESA_query_driver", "EGL_WL_bind_wayland_display", ""], smithay_module: renderer_egl, smithay_module: backend_egl
Apr 21 20:39:20.819 INFO Initializing a xkbcommon handler with keymap query, options: None, variant: , layout: , model: , rules: , smithay_module: xkbcommon_handler, seat_name: seat0, smithay_module: seat_handler
Apr 21 20:39:20.821 INFO Loaded Keymap, name: English (US), smithay_module: xkbcommon_handler, seat_name: seat0, smithay_module: seat_handler
Apr 21 20:39:20.822 INFO Creating new wl_output, name: Drm, smithay_module: output_handler
Apr 21 20:39:20.933 INFO Initializing a libinput backend, smithay_module: backend_libinput
Apr 21 20:39:20.933 INFO New input handler set, smithay_module: backend_libinput
Apr 21 20:39:22.358 INFO New device "event1" on seat "default", smithay_module: backend_libinput
Apr 21 20:39:22.358 INFO New device "event2" on seat "default", smithay_module: backend_libinput
Apr 21 20:39:22.358 INFO New device "event0" on seat "default", smithay_module: backend_libinput
Apr 21 20:39:22.358 INFO New device "event8" on seat "default", smithay_module: backend_libinput
Apr 21 20:39:22.358 INFO New device "event11" on seat "default", smithay_module: backend_libinput
Apr 21 20:39:22.358 INFO New device "event12" on seat "default", smithay_module: backend_libinput
Apr 21 20:39:22.358 INFO New device "event13" on seat "default", smithay_module: backend_libinput
Apr 21 20:39:22.358 INFO New device "event14" on seat "default", smithay_module: backend_libinput
Apr 21 20:39:22.358 INFO New device "event6" on seat "default", smithay_module: backend_libinput
Apr 21 20:39:22.358 INFO New device "event7" on seat "default", smithay_module: backend_libinput
Apr 21 20:39:22.358 INFO New device "event3" on seat "default", smithay_module: backend_libinput
Apr 21 20:39:22.358 INFO New device "event4" on seat "default", smithay_module: backend_libinput
Apr 21 20:39:22.358 INFO New device "event5" on seat "default", smithay_module: backend_libinput
Apr 21 20:39:22.358 INFO New device "event9" on seat "default", smithay_module: backend_libinput
Apr 21 20:39:22.358 INFO New device "event10" on seat "default", smithay_module: backend_libinput
Apr 21 20:39:22.358 INFO New device "event22" on seat "default", smithay_module: backend_libinput
Apr 21 20:39:22.358 INFO New device "event23" on seat "default", smithay_module: backend_libinput
Apr 21 20:39:22.358 INFO New device "event24" on seat "default", smithay_module: backend_libinput
Apr 21 20:39:22.358 INFO New device "event25" on seat "default", smithay_module: backend_libinput
Apr 21 20:39:22.358 INFO New device "event20" on seat "default", smithay_module: backend_libinput
Apr 21 20:39:22.359 INFO New device "event21" on seat "default", smithay_module: backend_libinput
Apr 21 20:39:22.359 INFO New device "event16" on seat "default", smithay_module: backend_libinput
Apr 21 20:39:22.359 INFO New device "event17" on seat "default", smithay_module: backend_libinput
Apr 21 20:39:22.359 INFO New device "event18" on seat "default", smithay_module: backend_libinput
Apr 21 20:39:22.359 INFO New device "event19" on seat "default", smithay_module: backend_libinput
Apr 21 20:39:53.792 INFO Device Changed, smithay_module: backend_udev
Apr 21 20:39:53.795 INFO Devnum: 1110001000000001, smithay_module: backend_udev
Apr 21 20:39:53.795 INFO Connected: HDMIA
Apr 21 20:39:53.795 INFO Connected: DisplayPort
Apr 21 20:39:53.795 INFO Initializing EglSurface, smithay_module: backend_egl
Apr 21 20:39:53.795 DEBG Trying to initialize EGL with OpenGLES 3.0, smithay_module: renderer_egl, smithay_module: renderer_egl, smithay_module: backend_egl
Apr 21 20:39:53.795 INFO Selected color format: PixelFormat { hardware_accelerated: true, color_bits: 24, alpha_bits: 8, depth_bits: 24, stencil_bits: 8, stereoscopy: false, multisampling: None, srgb: false }, smithay_module: renderer_egl, smithay_module: backend_egl
Apr 21 20:39:53.796 INFO EGL context created, smithay_module: renderer_egl, smithay_module: renderer_egl, smithay_module: renderer_egl, smithay_module: backend_egl
thread 'Apr 21 20:39:53.796main ' panicked at 'INFOcalled `Result::unwrap()` on an `Err` value: EGL(SurfaceCreationFailed) ', Initializing GbmSurfaceanvil/src/udev.rs, :smithay_module345:: 29backend_gbm

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Apr 21 20:39:53.796 ERRO EGL surface creation failed: Underlying error: Crtc `crtc::Handle(47)` is already in use by another backend, smithay_module: renderer_egl, smithay_module: backend_egl
Apr 21 20:39:53.796 INFO Closing logind session, vt: None, seat: seat0, id: 3, session_type: logind, smithay_module: backend_session, session_type: auto, smithay_module: backend_session_auto
```

**Comment by Drakulix** [comment]
Hot-plugging is a whole different problem in anvil :sweat_smile:  (not smithay in general)

Can you run the first testcase with  `RUST_BACKTRACE=1`? I have a suspicion, but would like to confirm it.

**Comment by PolyMeilex** [comment]
Sorry for late reply
```
Apr 22 16:43:45.185 INFO Starting anvil on a tty using udev
Apr 22 16:43:45.185 INFO Listening on wayland socket, name: wayland-0
Apr 22 16:43:45.185 INFO Trying to create logind session, session_type: auto, smithay_module: backend_session_auto
Apr 22 16:43:45.230 INFO DrmDevice initializing, smithay_module: backend_drm
Apr 22 16:43:45.230 WARN Unable to become drm master, assuming unpriviledged mode, smithay_module: backend_drm
Apr 22 16:43:45.230 DEBG Creating gbm device, smithay_module: backend_gbm
Apr 22 16:43:45.436 DEBG Creating egl context from device, smithay_module: backend_egl
Apr 22 16:43:45.500 DEBG EGL No-Display Extensions: ["EGL_EXT_platform_base", "EGL_EXT_device_base", "EGL_EXT_device_enumeration", "EGL_EXT_device_query", "EGL_KHR_client_get_all_proc_addresses", "EGL_EXT_client_extensions", "EGL_KHR_debug", "EGL_KHR_platform_x11", "EGL_EXT_platform_x11", "EGL_EXT_platform_device", "EGL_KHR_platform_wayland", "EGL_EXT_platform_wayland", "EGL_MESA_platform_gbm", "EGL_MESA_platform_surfaceless"], smithay_module: renderer_egl, smithay_module: backend_egl
Apr 22 16:43:45.503 INFO EGL Initialized, smithay_module: renderer_egl, smithay_module: backend_egl
Apr 22 16:43:45.503 INFO EGL Version: (1, 5), smithay_module: renderer_egl, smithay_module: backend_egl
Apr 22 16:43:45.503 INFO EGL Extensions: ["EGL_ANDROID_blob_cache", "EGL_EXT_buffer_age", "EGL_EXT_create_context_robustness", "EGL_EXT_image_dma_buf_import", "EGL_EXT_image_dma_buf_import_modifiers", "EGL_KHR_cl_event2", "EGL_KHR_config_attribs", "EGL_KHR_create_context", "EGL_KHR_create_context_no_error", "EGL_KHR_fence_sync", "EGL_KHR_get_all_proc_addresses", "EGL_KHR_gl_colorspace", "EGL_KHR_gl_renderbuffer_image", "EGL_KHR_gl_texture_2D_image", "EGL_KHR_gl_texture_3D_image", "EGL_KHR_gl_texture_cubemap_image", "EGL_KHR_image", "EGL_KHR_image_base", "EGL_KHR_image_pixmap", "EGL_KHR_no_config_context", "EGL_KHR_reusable_sync", "EGL_KHR_surfaceless_context", "EGL_EXT_pixel_format_float", "EGL_KHR_wait_sync", "EGL_MESA_configless_context", "EGL_MESA_drm_image", "EGL_MESA_image_dma_buf_export", "EGL_MESA_query_driver", "EGL_WL_bind_wayland_display", ""], smithay_module: renderer_egl, smithay_module: backend_egl
Apr 22 16:43:45.504 INFO Connected: HDMIA
Apr 22 16:43:45.504 INFO Connected: DisplayPort
Apr 22 16:43:45.504 INFO Initializing EglSurface, smithay_module: backend_egl
Apr 22 16:43:45.504 DEBG Trying to initialize EGL with OpenGLES 3.0, smithay_module: renderer_egl, smithay_module: renderer_egl, smithay_module: backend_egl
Apr 22 16:43:45.504 INFO Selected color format: PixelFormat { hardware_accelerated: true, color_bits: 24, alpha_bits: 8, depth_bits: 24, stencil_bits: 8, stereoscopy: false, multisampling: None, srgb: false }, smithay_module: renderer_egl, smithay_module: backend_egl
Apr 22 16:43:45.514 INFO EGL context created, smithay_module: renderer_egl, smithay_module: renderer_egl, smithay_module: renderer_egl, smithay_module: backend_egl
Apr 22 16:43:45.514 INFO Initializing GbmSurface, smithay_module: backend_gbm
Apr 22 16:43:45.515 DEBG EGL surface successfully created, smithay_module: renderer_egl, smithay_module: backend_egl
Apr 22 16:43:45.836 INFO Initializing EglSurface, smithay_module: backend_egl
Apr 22 16:43:45.836 DEBG Trying to initialize EGL with OpenGLES 3.0, smithay_module: renderer_egl, smithay_module: renderer_egl, smithay_module: backend_egl
Apr 22 16:43:45.836 INFO Selected color format: PixelFormat { hardware_accelerated: true, color_bits: 24, alpha_bits: 8, depth_bits: 24, stencil_bits: 8, stereoscopy: false, multisampling: None, srgb: false }, smithay_module: renderer_egl, smithay_module: backend_egl
Apr 22 16:43:45.836 INFO EGL context created, smithay_module: renderer_egl, smithay_module: renderer_egl, smithay_module: renderer_egl, smithay_module: backend_egl
Apr 22 16:43:45.837 INFO Initializing GbmSurface, smithay_module: backend_gbm
Apr 22 16:43:45.837 DEBG EGL surface successfully created, smithay_module: renderer_egl, smithay_module: backend_egl
Apr 22 16:43:45.847 INFO Initializing EglSurface, smithay_module: backend_egl
Apr 22 16:43:45.848 DEBG Trying to initialize EGL with OpenGLES 3.0, smithay_module: renderer_egl, smithay_module: renderer_egl, smithay_module: backend_egl
Apr 22 16:43:45.848 INFO Selected color format: PixelFormat { hardware_accelerated: true, color_bits: 24, alpha_bits: 8, depth_bits: 24, stencil_bits: 8, stereoscopy: false, multisampling: None, srgb: false }, smithay_module: renderer_egl, smithay_module: backend_egl
Apr 22 16:43:45.848 INFO EGL context created, smithay_module: renderer_egl, smithay_module: renderer_egl, smithay_module: renderer_egl, smithay_module: backend_egl
Apr 22 16:43:45.848 INFO Initializing GbmSurface, smithay_module: backend_gbm
Apr 22 16:43:45.848 DEBG EGL surface successfully created, smithay_module: renderer_egl, smithay_module: backend_egl
Apr 22 16:43:45.854 DEBG Importing cursor, crtc: crtc::Handle(63), smithay_module: backend_gbm
[src/backend/drm/legacy/surface.rs:270] x = Unknown {
    errno: EBUSY,
}
thread 'Apr 22 16:43:45.854main' panicked at 'called `Result::unwrap()` on an `Err` value: ContextLost',  anvil/src/udev.rsDEBG: 470Commiting new state:21
, crtcstack backtrace:
: crtc::Handle(63), smithay_module: backend_gbm
Apr 22 16:43:45.854 DEBG Setting screen, crtc: crtc::Handle(63), smithay_module: backend_drm
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1052
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:472
  11: rust_begin_unwind
             at src/libstd/panicking.rs:380
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  13: core::option::expect_none_failed
             at src/libcore/option.rs:1199
  14: core::result::Result<T,E>::unwrap
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/result.rs:963
  15: <anvil::udev::UdevHandlerImpl<S,Data> as smithay::backend::udev::UdevHandler>::device_added
             at anvil/src/udev.rs:470
  16: smithay::backend::udev::UdevBackend<T>::new::{{closure}}
             at ./src/backend/udev.rs:64
  17: core::iter::adapters::map_fold::{{closure}}
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/iter/adapters/mod.rs:772
  18: core::iter::traits::iterator::Iterator::fold::ok::{{closure}}
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/iter/traits/iterator.rs:1900
  19: core::iter::traits::iterator::Iterator::try_fold
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/iter/traits/iterator.rs:1776
  20: core::iter::traits::iterator::Iterator::fold
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/iter/traits/iterator.rs:1903
  21: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/iter/adapters/mod.rs:812
  22: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/iter/adapters/mod.rs:812
  23: <core::iter::adapters::chain::Chain<A,B> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/iter/adapters/chain.rs:118
  24: <core::iter::adapters::chain::Chain<A,B> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/iter/adapters/chain.rs:112
  25: <core::iter::adapters::flatten::FlattenCompat<I,U> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/iter/adapters/flatten.rs:334
  26: <core::iter::adapters::flatten::FlatMap<I,U,F> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/iter/adapters/flatten.rs:78
  27: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/iter/adapters/mod.rs:812
  28: core::iter::traits::iterator::Iterator::for_each
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/iter/traits/iterator.rs:655
  29: <hashbrown::map::HashMap<K,V,S> as core::iter::traits::collect::Extend<(K, V)>>::extend
             at /cargo/registry/src/github.com-1ecc6299db9ec823/hashbrown-0.6.2/src/map.rs:2578
  30: <std::collections::hash::map::HashMap<K,V,S> as core::iter::traits::collect::Extend<(K, V)>>::extend
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/collections/hash/map.rs:2390
  31: <std::collections::hash::set::HashSet<T,S> as core::iter::traits::collect::Extend<T>>::extend
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/collections/hash/set.rs:961
  32: <std::collections::hash::set::HashSet<T,S> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/collections/hash/set.rs:948
  33: core::iter::traits::iterator::Iterator::collect
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/iter/traits/iterator.rs:1558
  34: smithay::backend::udev::UdevBackend<T>::new
             at ./src/backend/udev.rs:59
  35: anvil::udev::run_udev
             at anvil/src/udev.rs:126
  36: anvil::main
             at anvil/src/main.rs:82
  37: std::rt::lang_start::{{closure}}
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/rt.rs:67
  38: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  39: std::panicking::try::do_call
             at src/libstd/panicking.rs:305
  40: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  41: std::panicking::try
             at src/libstd/panicking.rs:281
  42: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  43: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  44: std::rt::lang_start
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/rt.rs:67
  45: main
  46: __libc_start_main
  47: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Apr 22 16:43:46.057 INFO Closing logind session, vt: None, seat: seat0, id: 1, session_type: logind, smithay_module: backend_session, session_type: auto, smithay_module: backend_session_auto
Apr 22 16:43:46.101 INFO Dropping device: Some("/dev/dri/card1"), smithay_module: backend_drm
Apr 22 16:43:46.101 ERRO Failed to reset crtc (crtc::Handle(55)). Error: permission denied, smithay_module: backend_drm
Apr 22 16:43:46.101 ERRO Failed to reset crtc (crtc::Handle(47)). Error: permission denied, smithay_module: backend_drm
```

**Comment by Drakulix** [comment]
Alright, so it seems we sometimes may get *EBUSY* from the drm-driver, if it is not ready to mode-set (initialize your monitor in that context).

Which is something we do not handle correctly in the new atomic-modeset backend, which we added very recently (#194).

In those cases we need to retry later.
This means two things need to be done in smithay:

- Try to bubble up `EBUSY`, so we can handle this on a compositor level. `glium` only gives us `ContextLost`, which makes it impossible to differentiate between errors.
    - A possible solution would be to silently ignore those errors on the glium side, but call `drm_handler.error()`.
- Actually handle the error in anvil and schedule a retry. (weston [tries 5 times over 5 seconds](https://gitlab.freedesktop.org/wayland/weston/-/merge_requests/27))

I will get to it.
