### ISSUE TITLE
Crash when double-clicking foot titlebar to fullscreen

### ISSUE THREAD

**Issue by chrisduerr** [Smithay/smithay#494]
I've run into this issue while debugging something else and am not interested in looking into this myself right now. But I thought it might still be of interest.

The following backtrace will be produced when opening the foot terminal emulator and double-clicking the titlebar to fullscreen it (reproducible on all backends):

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/desktop/utils.rs:150:57
stack backtrace:
   0: rust_begin_unwind
             at /rustc/2681f253bcdb31a274411d2be456e7c6a1c67d62/library/std/src/panicking.rs:577:5
   1: core::panicking::panic_fmt
             at /rustc/2681f253bcdb31a274411d2be456e7c6a1c67d62/library/core/src/panicking.rs:135:14
   2: core::panicking::panic
             at /rustc/2681f253bcdb31a274411d2be456e7c6a1c67d62/library/core/src/panicking.rs:48:5
   3: core::option::Option<T>::unwrap
             at /rustc/2681f253bcdb31a274411d2be456e7c6a1c67d62/library/core/src/option.rs:752:21
   4: smithay::desktop::utils::damage_from_surface_tree::{{closure}}::{{closure}}
             at /home/undeadleech/programming/rust/smithay/src/desktop/utils.rs:150:34
   5: core::iter::adapters::map::map_fold::{{closure}}
             at /rustc/2681f253bcdb31a274411d2be456e7c6a1c67d62/library/core/src/iter/adapters/map.rs:84:28
   6: core::iter::traits::iterator::Iterator::fold
             at /rustc/2681f253bcdb31a274411d2be456e7c6a1c67d62/library/core/src/iter/traits/iterator.rs:2203:21
   7: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/2681f253bcdb31a274411d2be456e7c6a1c67d62/library/core/src/iter/adapters/map.rs:124:9
   8: core::iter::traits::iterator::Iterator::for_each
             at /rustc/2681f253bcdb31a274411d2be456e7c6a1c67d62/library/core/src/iter/traits/iterator.rs:772:9
   9: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
             at /rustc/2681f253bcdb31a274411d2be456e7c6a1c67d62/library/alloc/src/vec/spec_extend.rs:40:17
  10: <alloc::vec::Vec<T,A> as core::iter::traits::collect::Extend<T>>::extend
             at /rustc/2681f253bcdb31a274411d2be456e7c6a1c67d62/library/alloc/src/vec/mod.rs:2618:9
  11: smithay::desktop::utils::damage_from_surface_tree::{{closure}}
             at /home/undeadleech/programming/rust/smithay/src/desktop/utils.rs:145:21
  12: smithay::wayland::compositor::tree::PrivateSurfaceData::map
             at /home/undeadleech/programming/rust/smithay/src/wayland/compositor/tree.rs:471:29
  13: smithay::wayland::compositor::tree::PrivateSurfaceData::map
             at /home/undeadleech/programming/rust/smithay/src/wayland/compositor/tree.rs:472:36
  14: smithay::wayland::compositor::tree::PrivateSurfaceData::map_tree
             at /home/undeadleech/programming/rust/smithay/src/wayland/compositor/tree.rs:425:9
  15: smithay::wayland::compositor::with_surface_tree_upward
             at /home/undeadleech/programming/rust/smithay/src/wayland/compositor/mod.rs:307:5
  16: smithay::desktop::utils::damage_from_surface_tree
             at /home/undeadleech/programming/rust/smithay/src/desktop/utils.rs:110:5
  17: smithay::desktop::window::Window::accumulated_damage
             at /home/undeadleech/programming/rust/smithay/src/desktop/window.rs:279:17
  18: smithay::desktop::space::window::<impl smithay::desktop::space::element::SpaceElement<R,F,E,T> for smithay::desktop::window::Window>::accumulated_damage
             at /home/undeadleech/programming/rust/smithay/src/desktop/space/window.rs:89:9
  19: smithay::desktop::space::Space::render_output
             at /home/undeadleech/programming/rust/smithay/src/desktop/space/mod.rs:483:31
  20: anvil::render::render_output
             at ./src/render.rs:76:9
  21: anvil::winit::run_winit::{{closure}}
             at ./src/winit.rs:227:17
  22: core::result::Result<T,E>::and_then
             at /rustc/2681f253bcdb31a274411d2be456e7c6a1c67d62/library/core/src/result.rs:1299:22
  23: anvil::winit::run_winit
             at ./src/winit.rs:225:30
  24: anvil::main
             at ./src/main.rs:31:13
  25: core::ops::function::FnOnce::call_once
             at /rustc/2681f253bcdb31a274411d2be456e7c6a1c67d62/library/core/src/ops/function.rs:227:5
```

This also causes a lock poison error:

<details>

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', src/wayland/compositor/tree.rs:101:48
stack backtrace:
   0:     0x55df121fa24c - std::backtrace_rs::backtrace::libunwind::trace::h67a47b07d69f130a
                               at /rustc/2681f253bcdb31a274411d2be456e7c6a1c67d62/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55df121fa24c - std::backtrace_rs::backtrace::trace_unsynchronized::h50a3c84950ec1ee1
                               at /rustc/2681f253bcdb31a274411d2be456e7c6a1c67d62/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55df121fa24c - std::sys_common::backtrace::_print_fmt::h3c76d524ef632745
                               at /rustc/2681f253bcdb31a274411d2be456e7c6a1c67d62/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55df121fa24c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h228b5f48623d286d
                               at /rustc/2681f253bcdb31a274411d2be456e7c6a1c67d62/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55df1222396c - core::fmt::write::h8a605b482b83fb30
                               at /rustc/2681f253bcdb31a274411d2be456e7c6a1c67d62/library/core/src/fmt/mod.rs:1190:17
   5:     0x55df121f4a93 - std::io::Write::write_fmt::h371da2bf57c6dd36
                               at /rustc/2681f253bcdb31a274411d2be456e7c6a1c67d62/library/std/src/io/mod.rs:1653:15
   6:     0x55df121fca52 - std::sys_common::backtrace::_print::hb591026100bd9540
                               at /rustc/2681f253bcdb31a274411d2be456e7c6a1c67d62/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55df121fca52 - std::sys_common::backtrace::print::ha6eac1cc5aa290a1
                               at /rustc/2681f253bcdb31a274411d2be456e7c6a1c67d62/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55df121fca52 - std::panicking::default_hook::{{closure}}::hd877bfa5180fd928
                               at /rustc/2681f253bcdb31a274411d2be456e7c6a1c67d62/library/std/src/panicking.rs:290:50
   9:     0x55df121fc635 - std::panicking::default_hook::hfdfec8854fa7e083
                               at /rustc/2681f253bcdb31a274411d2be456e7c6a1c67d62/library/std/src/panicking.rs:307:9
  10:     0x55df121fd104 - std::panicking::rust_panic_with_hook::h50bc5bc849ffa979
                               at /rustc/2681f253bcdb31a274411d2be456e7c6a1c67d62/library/std/src/panicking.rs:691:17
  11:     0x55df121fcde7 - std::panicking::begin_panic_handler::{{closure}}::h7c4b002c065a3bae
                               at /rustc/2681f253bcdb31a274411d2be456e7c6a1c67d62/library/std/src/panicking.rs:581:13
  12:     0x55df121fa6f4 - std::sys_common::backtrace::__rust_end_short_backtrace::h3f18aa108fa8182f
                               at /rustc/2681f253bcdb31a274411d2be456e7c6a1c67d62/library/std/src/sys_common/backtrace.rs:139:18
  13:     0x55df121fcaf9 - rust_begin_unwind
                               at /rustc/2681f253bcdb31a274411d2be456e7c6a1c67d62/library/std/src/panicking.rs:577:5
  14:     0x55df1153fc33 - core::panicking::panic_fmt::h0d806a9fb7094cd2
                               at /rustc/2681f253bcdb31a274411d2be456e7c6a1c67d62/library/core/src/panicking.rs:135:14
  15:     0x55df1153fd23 - core::result::unwrap_failed::h36dde8598c37de99
                               at /rustc/2681f253bcdb31a274411d2be456e7c6a1c67d62/library/core/src/result.rs:1737:5
  16:     0x55df11993bd1 - core::result::Result<T,E>::unwrap::hb79b75e8a767279e
                               at /rustc/2681f253bcdb31a274411d2be456e7c6a1c67d62/library/core/src/result.rs:1065:23
  17:     0x55df11ab32f3 - smithay::wayland::compositor::tree::PrivateSurfaceData::cleanup::hde5ba9fdca59b52a
                               at /home/undeadleech/programming/rust/smithay/src/wayland/compositor/tree.rs:101:27
  18:     0x55df117ef190 - smithay::wayland::compositor::handlers::implement_surface::{{closure}}::h51ff51e60124659f
                               at /home/undeadleech/programming/rust/smithay/src/wayland/compositor/handlers.rs:216:59
  19:     0x55df1169f47a - wayland_commons::filter::Filter<E>::send::h78b66f0572a72841
                               at /home/undeadleech/.cargo/registry/src/github.com-1ecc6299db9ec823/wayland-commons-0.29.1/src/filter.rs:100:13
  20:     0x55df118abda5 - wayland_server::imp::resource::ResourceInner::assign_destructor::{{closure}}::h39cd1084bfd03887
                               at /home/undeadleech/.cargo/registry/src/github.com-1ecc6299db9ec823/wayland-server-0.29.1/src/native_lib/resource.rs:283:48
  21:     0x55df1201ed07 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::he21f398e8924ed9c
                               at /rustc/2681f253bcdb31a274411d2be456e7c6a1c67d62/library/alloc/src/boxed.rs:1868:9
  22:     0x55df120189ba - wayland_server::imp::resource::resource_destroy::{{closure}}::h06c4beec3b5bb083
                               at /home/undeadleech/.cargo/registry/src/github.com-1ecc6299db9ec823/wayland-server-0.29.1/src/native_lib/resource.rs:401:17
  23:     0x55df120506bc - std::panicking::try::do_call::hc73220fdecce7336
                               at /rustc/2681f253bcdb31a274411d2be456e7c6a1c67d62/library/std/src/panicking.rs:485:40
  24:     0x55df1205171b - __rust_try
  25:     0x55df1204eb7d - std::panicking::try::h41f6108e46883c84
                               at /rustc/2681f253bcdb31a274411d2be456e7c6a1c67d62/library/std/src/panicking.rs:449:19
  26:     0x55df12040c64 - std::panic::catch_unwind::hf931386a05d23c10
                               at /rustc/2681f253bcdb31a274411d2be456e7c6a1c67d62/library/std/src/panic.rs:136:14
  27:     0x55df12017eb0 - wayland_server::imp::resource::resource_destroy::h6b900e6f16e31c5d
                               at /home/undeadleech/.cargo/registry/src/github.com-1ecc6299db9ec823/wayland-server-0.29.1/src/native_lib/resource.rs:389:15
  28:     0x7f270e78a89a - <unknown>
  29:     0x7f270e790ec0 - <unknown>
  30:     0x7f270e7913e0 - <unknown>
  31:     0x7f270e78b30e - wl_client_destroy
  32:     0x7f270e78bd8f - wl_display_destroy_clients
  33:     0x55df12025672 - <wayland_server::imp::display::DisplayInner as core::ops::drop::Drop>::drop::h55ffbc3e556e8d46
                               at /home/undeadleech/.cargo/registry/src/github.com-1ecc6299db9ec823/wayland-server-0.29.1/src/native_lib/display.rs:28:17
  34:     0x55df115a7b67 - core::ptr::drop_in_place<wayland_server::imp::display::DisplayInner>::h2becf17a8d0b4616
                               at /rustc/2681f253bcdb31a274411d2be456e7c6a1c67d62/library/core/src/ptr/mod.rs:188:1
  35:     0x55df115a4bdb - core::ptr::drop_in_place<wayland_server::display::Display>::h001954aaa6511751
                               at /rustc/2681f253bcdb31a274411d2be456e7c6a1c67d62/library/core/src/ptr/mod.rs:188:1
  36:     0x55df115ac98b - core::ptr::drop_in_place<core::cell::UnsafeCell<wayland_server::display::Display>>::hb0b12b4e55c45dbb
                               at /rustc/2681f253bcdb31a274411d2be456e7c6a1c67d62/library/core/src/ptr/mod.rs:188:1
  37:     0x55df115ac50f - core::ptr::drop_in_place<core::cell::RefCell<wayland_server::display::Display>>::h9619045bc329a2ae
                               at /rustc/2681f253bcdb31a274411d2be456e7c6a1c67d62/library/core/src/ptr/mod.rs:188:1
  38:     0x55df115b8776 - <alloc::rc::Rc<T> as core::ops::drop::Drop>::drop::h63cd1feb9c02d8c4
                               at /rustc/2681f253bcdb31a274411d2be456e7c6a1c67d62/library/alloc/src/rc.rs:1476:17
  39:     0x55df1158f51b - core::ptr::drop_in_place<alloc::rc::Rc<core::cell::RefCell<wayland_server::display::Display>>>::hf419710908974281
                               at /rustc/2681f253bcdb31a274411d2be456e7c6a1c67d62/library/core/src/ptr/mod.rs:188:1
  40:     0x55df1155fabe - anvil::winit::run_winit::h0a49426334573fa3
                               at /home/undeadleech/programming/rust/smithay/anvil/src/winit.rs:278:1
  41:     0x55df1154815d - anvil::main::h239009b2f9d63df7
                               at /home/undeadleech/programming/rust/smithay/anvil/src/main.rs:31:13
  42:     0x55df11542c2b - core::ops::function::FnOnce::call_once::hc5168ee654e68bdc
                               at /rustc/2681f253bcdb31a274411d2be456e7c6a1c67d62/library/core/src/ops/function.rs:227:5
  43:     0x55df1155807e - std::sys_common::backtrace::__rust_begin_short_backtrace::h3002ef3f30b904b2
                               at /rustc/2681f253bcdb31a274411d2be456e7c6a1c67d62/library/std/src/sys_common/backtrace.rs:123:18
  44:     0x55df11549f51 - std::rt::lang_start::{{closure}}::h21b6474c59c1e81f
                               at /rustc/2681f253bcdb31a274411d2be456e7c6a1c67d62/library/std/src/rt.rs:145:18
  45:     0x55df121f9907 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::ha5e2a0678cb10b15
                               at /rustc/2681f253bcdb31a274411d2be456e7c6a1c67d62/library/core/src/ops/function.rs:259:13
  46:     0x55df121f9907 - std::panicking::try::do_call::h957c9055ce253210
                               at /rustc/2681f253bcdb31a274411d2be456e7c6a1c67d62/library/std/src/panicking.rs:485:40
  47:     0x55df121f9907 - std::panicking::try::h669d8bf4e9ae5cd2
                               at /rustc/2681f253bcdb31a274411d2be456e7c6a1c67d62/library/std/src/panicking.rs:449:19
  48:     0x55df121f9907 - std::panic::catch_unwind::hca0c1aa444a25f78
                               at /rustc/2681f253bcdb31a274411d2be456e7c6a1c67d62/library/std/src/panic.rs:136:14
  49:     0x55df121f9907 - std::rt::lang_start_internal::{{closure}}::h24e59230913b19d4
                               at /rustc/2681f253bcdb31a274411d2be456e7c6a1c67d62/library/std/src/rt.rs:128:48
  50:     0x55df121f9907 - std::panicking::try::do_call::hb3b656608bd9879a
                               at /rustc/2681f253bcdb31a274411d2be456e7c6a1c67d62/library/std/src/panicking.rs:485:40
  51:     0x55df121f9907 - std::panicking::try::ha2ec51fa3cb35115
                               at /rustc/2681f253bcdb31a274411d2be456e7c6a1c67d62/library/std/src/panicking.rs:449:19
  52:     0x55df121f9907 - std::panic::catch_unwind::ha900af64645e3a41
                               at /rustc/2681f253bcdb31a274411d2be456e7c6a1c67d62/library/std/src/panic.rs:136:14
  53:     0x55df121f9907 - std::rt::lang_start_internal::h38638f0eb6963580
                               at /rustc/2681f253bcdb31a274411d2be456e7c6a1c67d62/library/std/src/rt.rs:128:20
  54:     0x55df11549f20 - std::rt::lang_start::h444f94533adf1436
                               at /rustc/2681f253bcdb31a274411d2be456e7c6a1c67d62/library/std/src/rt.rs:144:17
  55:     0x55df115487ec - main
  56:     0x7f270ea53b25 - __libc_start_main
  57:     0x55df1154045e - _start
  58:                0x0 - <unknown>
```

</details>

**Comment by i509VCB** [comment]
Protocol log: https://gist.github.com/i509VCB/63774503e86e011b4c0f43cdc8e65852

**Comment by i509VCB** [comment]
Pretty sure the cause is the null buffer attached to wl_surface@24

```
[3101140.093]  -> wl_surface@24.attach(nil, 0, 0)
[3101140.102]  -> wl_surface@24.commit()
```

**Comment by i509VCB** [comment]
It appears that `wleird-unmap` also causes this panic.
