### ISSUE TITLE
libegl-mesa segfault on debian

### ISSUE THREAD

**Issue by paulfariello** [Smithay/smithay#657]
While trying to run ``anvil --x11`` a segfault occurs in libegl-mesa. Not sure this is smithay fault but anyway:

```
RUST_LOG=debug target/debug/anvil --x11                                                                                                                                 <<<
Jul 05 08:22:52.886 INFO Starting anvil with x11 backend
Jul 05 08:22:52.887 INFO Connecting to the X server, smithay_module: backend_x11
Jul 05 08:22:52.889 INFO Connected to screen 0, smithay_module: backend_x11
Jul 05 08:22:52.890 INFO Loaded extension Present version 1.0, smithay_module: backend_x11
Jul 05 08:22:52.891 INFO Loaded extension XFIXES version 4.0, smithay_module: backend_x11
Jul 05 08:22:52.891 INFO Loaded extension DRI3 version 1.2, smithay_module: backend_x11
Jul 05 08:22:52.894 DEBG Supported EGL client extensions: ["EGL_EXT_device_base", "EGL_EXT_device_enumeration", "EGL_EXT_device_query", "EGL_EXT_platform_base", "EGL_KHR_client_get_all_proc_addresses", "EGL_EXT_client_extensions", "EGL_KHR_debug", "EGL_EXT_platform_device", "EGL_EXT_platform_wayland", "EGL_KHR_platform_wayland", "EGL_EXT_platform_x11", "EGL_KHR_platform_x11", "EGL_MESA_platform_gbm", "EGL_KHR_platform_gbm", "EGL_MESA_platform_surfaceless"], smithay_module: backend_egl
[1]  2879417 segmentation fault (core dumped)  RUST_LOG=debug target/debug/anvil --x11
```

Tracing with gdb:
```
Thread 1 "anvil" received signal SIGSEGV, Segmentation fault.
dri2_find_screen_for_display (fallback_screen=0, disp=0x5555568cab40) at ../src/egl/drivers/dri2/platform_x11.c:1215
1215	      if (attr[0] == EGL_PLATFORM_X11_SCREEN_EXT)
(gdb) bt
#0  dri2_find_screen_for_display (fallback_screen=0, disp=0x5555568cab40) at ../src/egl/drivers/dri2/platform_x11.c:1215
#1  dri2_get_xcb_connection (disp=disp@entry=0x5555568cab40, dri2_dpy=dri2_dpy@entry=0x5555568cb900) at ../src/egl/drivers/dri2/platform_x11.c:1234
#2  0x00007ffff6e9f8ae in dri2_initialize_x11_dri3 (disp=0x5555568cab40) at ../src/egl/drivers/dri2/platform_x11.c:1359
#3  dri2_initialize_x11 (disp=disp@entry=0x5555568cab40) at ../src/egl/drivers/dri2/platform_x11.c:1535
#4  0x00007ffff6e9a198 in dri2_initialize (disp=0x5555568cab40) at ../src/egl/drivers/dri2/egl_dri2.c:1184
#5  dri2_initialize (disp=disp@entry=0x5555568cab40) at ../src/egl/drivers/dri2/egl_dri2.c:1152
#6  0x00007ffff6e92a6c in eglInitialize (dpy=0x5555568cab40, major=0x7ffffffe9730, minor=0x7ffffffe9734) at ../src/egl/main/eglapi.c:630
#7  0x0000555555bcc791 in smithay::backend::egl::ffi::egl::Initialize (dpy=0x5555568cab40, major=0x7ffffffe9730, minor=0x7ffffffe9734)
    at target/debug/build/smithay-2fde4460287031d2/out/egl_bindings.rs:429
#8  0x0000555555cec6a9 in smithay::backend::egl::display::{impl#4}::new::{closure#0}<smithay::backend::egl::native::X11DefaultDisplay, core::option::Option<slog::Logger<alloc::sync::Arc<dyn slog::SendSyncRefUnwindSafeDrain<Ok=(), Err=slog::private::NeverStruct>>>>> () at src/backend/egl/display.rs:165
#9  0x0000555555c71247 in smithay::backend::egl::error::wrap_egl_call<u32, smithay::backend::egl::display::{impl#4}::new::{closure_env#0}<smithay::backend::egl::native::X11DefaultDisplay, core::option::Option<slog::Logger<alloc::sync::Arc<dyn slog::SendSyncRefUnwindSafeDrain<Ok=(), Err=slog::private::NeverStruct>>>>>>Python Exception <class 'gdb.MemoryError'> Cannot access memory at address 0x6:

    (call=#10 0x0000555555cea43f in smithay::backend::egl::display::EGLDisplay::new<smithay::backend::egl::native::X11DefaultDisplay, core::option::Option<slog::Logger<alloc::sync::Arc<dyn slog::SendSyncRefUnwindSafeDrain<Ok=(), Err=slog::private::NeverStruct>>>>> (native=0x5555564ed56a, logger=...) at src/backend/egl/display.rs:164
#11 0x0000555555bb5442 in smithay::backend::x11::egl_init () at src/backend/x11/mod.rs:930
#12 0x0000555555bb48cd in smithay::backend::x11::X11Handle::drm_node (self=0x7ffffffead70) at src/backend/x11/mod.rs:338
#13 0x00005555557d4f0e in anvil::x11::run_x11 (log=...) at anvil/src/x11.rs:99
#14 0x00005555556b57db in anvil::main () at anvil/src/main.rs:41
```

I can share more info if needed. Just tell me what is needed.

**Comment by Drakulix** [comment]
This is likely the same issue as https://github.com/Smithay/smithay/issues/438

In a nutshell debians mesa version is too old and since it is a now unsupported by upstream the issue sadly won't get resolved.

smithay also won't make an attempt at supporting outdated mesa version, as we also have to keep up with maintenance.

I wish I could tell you otherwise, but this is a "Won't fix". Sorry

**Comment by paulfariello** [comment]
Closing the issue. Sorry for duplicating issue.
