### ISSUE TITLE
Anvil crashing on tty switch off of it and back

### ISSUE THREAD

**Issue by ids1024** [Smithay/smithay#907]
This seems to be happening for me since https://github.com/Smithay/smithay/pull/760.

```
2023-02-24T17:16:55.032058Z  WARN anvil::udev: Error during rendering: ContextLost(PrimaryPlaneTestFailed)
thread 'main' panicked at 'Rendering loop lost: Testing the primary plane failed', anvil/src/udev.rs:1230:63
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I'm not really sure how the compositor is supposed to handle losing control of DRM device on tty switch and then re-configuring planes on the switch back, but I guess that isn't being handled correctly.

And if other people aren't seeing this issue... would it be hardware related, based on what planes the DRM device offers?

**Comment by ids1024** [comment]
The `PrimaryPlaneTestFailed` error is generated in 4 places, two of which have a `warn!` before returning the error, and two which don't. (This is something that could be improved in error handling in Smithay; it's not always clear where the error was generated and exactly what the underlying cause is.)

But it seems to be this spot where it returns the error:

```rust
        if !next_frame_state
            .test_state(
                &self.surface,
                self.planes.primary.handle,
                primary_plane_state,
                self.surface.commit_pending(),
            )
            .map_err(FrameError::DrmError)?
        {
            return Err(RenderFrameError::PrepareFrame(FrameError::PrimaryPlaneTestFailed));
        }   
```

**Comment by Drakulix** [comment]
cc @cmeissl

**Comment by cmeissl** [comment]
@ids1024 does it also happen when you disable the DrmCompositor? This can be done with ANVIL_DISABLE_DRM_COMPOSITOR=1

**Comment by ids1024** [comment]
With that set a tty switch seems to work, though I am seeing a different crash some of the time. Here's the last one I saw:

```
2023-02-24T22:56:16.036724Z  WARN drm_device:drm_atomic:create_surface:drm_atomic:commit: smithay::backend::drm::surface::atomic: New screen configuration invalid!:
	AtomicModeReq {
    objects: [
        50,
        70,
    ],
    count_props_per_object: [
        11,
        2,
    ],
    props: [
        property::Handle(
            9,
        ),
        property::Handle(
            10,
        ),
        property::Handle(
            11,
        ),
        property::Handle(
            12,
        ),
        property::Handle(
            13,
        ),
        property::Handle(
            14,
        ),
        property::Handle(
            15,
        ),
        property::Handle(
            16,
        ),
        property::Handle(
            17,
        ),
        property::Handle(
            20,
        ),
        property::Handle(
            54,
        ),
        property::Handle(
            22,
        ),
        property::Handle(
            23,
        ),
    ],
    values: [
        0,
        0,
        167772160,
        94371840,
        0,
        0,
        2560,
        1440,
        374,
        70,
        1,
        1,
        371,
    ],
}
	Atomic Test failed for new properties on crtc (crtc::Handle(70))
 device=Some("/dev/dri/card0") crtc=crtc::Handle(70) mode=Mode { name: "2560x1440", clock: 241500, size: (2560, 1440), hsync: (2608, 2640, 2720), vsync: (1443, 1448, 1481), hskew: 0, vscan: 0, vrefresh: 60, mode_type: PREFERRED | DRIVER } connectors=[connector::Handle(110)] crtc=crtc::Handle(70) event=true
2023-02-24T22:56:16.036876Z  WARN anvil::udev: Error during rendering: ContextLost(TestFailed(crtc::Handle(70)))
thread 'main' panicked at 'Rendering loop lost: Atomic Test failed for new properties on crtc (crtc::Handle(70))', anvil/src/udev.rs:1229:63
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This is with 3 outputs (laptop and two external monitors).

**Comment by ids1024** [comment]
Seems to happen regardless of external monitors. Are other people seeing the same behavior, or is it somehow more hardware specific?
